#!/bin/bash
#chmod -x filename

# Build and compile the visualizer library
cd /home/hank/dev/MachLib/_BUILD
rm CMakeCache.txt cmake_install.cmake libMachLib.a Makefile
rm -r CMakeFiles
cmake -G"Unix Makefiles" ..
make

# Build and compile the example project
cd /home/hank/dev/MachLib/example/_BUILD
rm CMakeCache.txt cmake_install.cmake Makefile
rm -r CMakeFiles
cmake -G"Unix Makefiles" ..
make
./ML_testing
